[build]
  command = "npm run build"  # Replace with your build command
  publish = "build"          # Replace with your build output directory

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
